/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _IndexRoute } from '../pages/';
import { Route as _MapRoute } from '../pages/map';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof _IndexRoute)['_inputType'];
    '/map': (typeof _MapRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof _IndexRoute)['_outputType'];
    '/map': (typeof _MapRoute)['_outputType'];
  }
}
